name: Deploy Docker Image on Self-Hosted

on:
  repository_dispatch:
    types:
      - deploy-docker-image
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: 'self-hosted-backend'
      url: 'https://nmstats.butr.link'
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker image pull ghcr.io/butr/nmstats;
          docker stack deploy --prune --resolve-image always -c /deploy/nmstats/docker-compose.yml nmstats;
